"""empty message

Revision ID: 011dce734fc1
Revises: 445066cb548c
Create Date: 2019-04-21 21:30:15.103327

"""

# revision identifiers, used by Alembic.
revision = '011dce734fc1'
down_revision = '445066cb548c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('keyword1', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('keyword2', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('keyword3', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('keyword4', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('keyword5', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('seg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'seg')
    op.drop_column('files', 'keyword5')
    op.drop_column('files', 'keyword4')
    op.drop_column('files', 'keyword3')
    op.drop_column('files', 'keyword2')
    op.drop_column('files', 'keyword1')
    # ### end Alembic commands ###
