"""empty message

Revision ID: 2491c2746123
Revises: b3f4baad024f
Create Date: 2019-05-10 21:01:19.118149

"""

# revision identifiers, used by Alembic.
revision = '2491c2746123'
down_revision = 'b3f4baad024f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
