"""empty message

Revision ID: 30099063659b
Revises: 286bd63cad67
Create Date: 2019-04-20 19:46:08.777836

"""

# revision identifiers, used by Alembic.
revision = '30099063659b'
down_revision = '286bd63cad67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
