"""empty message

Revision ID: 31f4a68bd8c2
Revises: f077f80ef934
Create Date: 2019-04-21 19:53:57.842735

"""

# revision identifiers, used by Alembic.
revision = '31f4a68bd8c2'
down_revision = 'f077f80ef934'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
