"""empty message

Revision ID: 445066cb548c
Revises: 31f4a68bd8c2
Create Date: 2019-04-21 20:50:25.802148

"""

# revision identifiers, used by Alembic.
revision = '445066cb548c'
down_revision = '31f4a68bd8c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_timestamp'), 'files', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_timestamp'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
