"""add email

Revision ID: 87f6d364e4e0
Revises: ec015035fe94
Create Date: 2019-04-18 21:36:40.482455

"""

# revision identifiers, used by Alembic.
revision = '87f6d364e4e0'
down_revision = 'ec015035fe94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
