"""empty message

Revision ID: b3f4baad024f
Revises: 430eec28bd10
Create Date: 2019-04-22 19:37:23.857068

"""

# revision identifiers, used by Alembic.
revision = 'b3f4baad024f'
down_revision = '430eec28bd10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('keyword_weight1', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('keyword_weight2', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('keyword_weight3', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('keyword_weight4', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('keyword_weight5', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'keyword_weight5')
    op.drop_column('files', 'keyword_weight4')
    op.drop_column('files', 'keyword_weight3')
    op.drop_column('files', 'keyword_weight2')
    op.drop_column('files', 'keyword_weight1')
    # ### end Alembic commands ###
