"""add register

Revision ID: ec015035fe94
Revises: a2c314ffabe9
Create Date: 2019-04-18 21:24:47.182219

"""

# revision identifiers, used by Alembic.
revision = 'ec015035fe94'
down_revision = 'a2c314ffabe9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
